//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsa4.Misc
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int client_id { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string firm_name { get; set; }
        public byte[] firm_logo { get; set; }
        public string firm_address { get; set; }
        public int request_id { get; set; }
        public int user_id { get; set; }
    
        public virtual request request { get; set; }
        public virtual user user { get; set; }
    }
}
