//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsa4.Misc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cursEntities : DbContext
    {
        public cursEntities()
            : base("name=cursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<depot> depots { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<loco> locoes { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<request_status> request_status { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<train> trains { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wagon> wagons { get; set; }
    }
}
