//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsa4.Misc
{
    using System;
    using System.Collections.Generic;
    
    public partial class train
    {
        public int train_id { get; set; }
        public int loco_id { get; set; }
        public int wagon_id { get; set; }
    
        public virtual loco loco { get; set; }
        public virtual wagon wagon { get; set; }
    }
}
